### ISSUE TITLE
Crawler Cannot Run! Missing Class! Please upload onto repository!

### ISSUE THREAD

**Issue by WorldClassTurd** [libbit702/crawler#1]
Fatal error: Class 'PHPUnit\Framework\TestCase' not found in G:\xampp\htdocs\crawler-master\tests\CrawlerVliveTest.php on line 10

**Comment by libbit702** [comment]
Hi, PHPUnit is a independent tool and you have to install it depending in your local environment. I chose phpunit5.7 as my php ver is 5.6。After a successful installation you could run the test cases like this:

➜ cd ROOT_OF_CRAWLER_DIRECTORY
➜ phpunit  tests/FILENAME_WITHOUT_PHP_EXTENSION

Pls check out the official site of phpunit [here](https://phpunit.de/) for more reference

**Comment by libbit702** [comment]
closed
